// India Defense Installations — Public/OSINT Data Only
// Sources: Wikipedia, Indian MoD Annual Reports, GlobalFirepower.com
// Part of Bharat Monitor India Intelligence Hub
//
// ⚠️ LEGAL DISCLAIMER: All coordinates sourced EXCLUSIVELY from
// public records, Wikipedia, and OpenStreetMap. No classified data.
// Compliance: Official Secrets Act (1923), National Map Policy.

import type { MilitaryBase } from '@/types';

// Indian Armed Forces domestic installations (publicly acknowledged)
export const INDIA_DEFENSE_INSTALLATIONS: MilitaryBase[] = [
    // ═══ ARMY HEADQUARTERS & COMMANDS ═══
    {
        id: 'india_army_hq',
        name: 'Army Headquarters (South Block)',
        lat: 28.6145,
        lon: 77.2066,
        type: 'india',
        country: 'India',
        arm: 'Indian Army HQ',
        status: 'active',
        description: 'Indian Army Headquarters, South Block, Raisina Hill, New Delhi.',
    },
    {
        id: 'india_northern_cmd',
        name: 'Northern Command HQ',
        lat: 32.9160,
        lon: 75.1400,
        type: 'india',
        country: 'India',
        arm: 'Indian Army',
        status: 'active',
        description: 'Udhampur, J&K. Covers LOC and LAC. Highest operational tempo command.',
    },
    {
        id: 'india_western_cmd',
        name: 'Western Command HQ',
        lat: 30.7110,
        lon: 76.8580,
        type: 'india',
        country: 'India',
        arm: 'Indian Army',
        status: 'active',
        description: 'Chandimandir, Haryana. Faces Pakistan Punjab border sector.',
    },
    {
        id: 'india_sw_cmd',
        name: 'South Western Command HQ',
        lat: 26.9124,
        lon: 75.7873,
        type: 'india',
        country: 'India',
        arm: 'Indian Army',
        status: 'active',
        description: 'Jaipur, Rajasthan. Thar Desert sector facing Pakistan.',
    },
    {
        id: 'india_southern_cmd',
        name: 'Southern Command HQ',
        lat: 18.5204,
        lon: 73.8567,
        type: 'india',
        country: 'India',
        arm: 'Indian Army',
        status: 'active',
        description: 'Pune, Maharashtra. Covers peninsular India.',
    },
    {
        id: 'india_central_cmd',
        name: 'Central Command HQ',
        lat: 26.8467,
        lon: 80.9462,
        type: 'india',
        country: 'India',
        arm: 'Indian Army',
        status: 'active',
        description: 'Lucknow, UP. Strategic reserve formations.',
    },
    {
        id: 'india_eastern_cmd',
        name: 'Eastern Command HQ (Fort William)',
        lat: 22.5557,
        lon: 88.3409,
        type: 'india',
        country: 'India',
        arm: 'Indian Army',
        status: 'active',
        description: 'Kolkata. Covers NE India, Arunachal LAC, Sikkim, Myanmar border.',
    },

    // ═══ MAJOR CANTONMENTS ═══
    {
        id: 'india_delhi_cantt',
        name: 'Delhi Cantonment',
        lat: 28.5905,
        lon: 77.1580,
        type: 'india',
        country: 'India',
        arm: 'Indian Army',
        status: 'active',
        description: 'Delhi Cantonment. Major garrison in national capital.',
    },
    {
        id: 'india_ambala_cantt',
        name: 'Ambala Cantonment',
        lat: 30.3782,
        lon: 76.7767,
        type: 'india',
        country: 'India',
        arm: 'Indian Army / IAF',
        status: 'active',
        description: 'Ambala, Haryana. Army garrison + IAF base (Rafale squadron).',
    },
    {
        id: 'india_meerut_cantt',
        name: 'Meerut Cantonment',
        lat: 28.9845,
        lon: 77.7064,
        type: 'india',
        country: 'India',
        arm: 'Indian Army',
        status: 'active',
        description: 'Meerut, UP. One of largest cantonments. Armored formations.',
    },
    {
        id: 'india_secunderabad_cantt',
        name: 'Secunderabad Cantonment',
        lat: 17.4399,
        lon: 78.4983,
        type: 'india',
        country: 'India',
        arm: 'Indian Army',
        status: 'active',
        description: 'Secunderabad, Telangana. Major southern garrison.',
    },

    // ═══ INDIAN NAVY — COMMANDS & BASES ═══
    {
        id: 'india_navy_western',
        name: 'Western Naval Command (INS Angre)',
        lat: 18.9256,
        lon: 72.8319,
        type: 'india',
        country: 'India',
        arm: 'Indian Navy',
        status: 'active',
        description: 'Mumbai. AOR: Arabian Sea, western Indian Ocean.',
    },
    {
        id: 'india_navy_eastern',
        name: 'Eastern Naval Command',
        lat: 17.7059,
        lon: 83.2978,
        type: 'india',
        country: 'India',
        arm: 'Indian Navy',
        status: 'active',
        description: 'Visakhapatnam. AOR: Bay of Bengal, eastern Indian Ocean.',
    },
    {
        id: 'india_navy_southern',
        name: 'Southern Naval Command (INS Venduruthy)',
        lat: 9.9631,
        lon: 76.2430,
        type: 'india',
        country: 'India',
        arm: 'Indian Navy',
        status: 'active',
        description: 'Kochi, Kerala. Training command.',
    },
    {
        id: 'india_karwar_kadamba',
        name: 'INS Kadamba (Karwar Naval Base)',
        lat: 14.8042,
        lon: 74.1219,
        type: 'india',
        country: 'India',
        arm: 'Indian Navy',
        status: 'active',
        description: "India's largest naval base. Project Seabird. Karnataka coast.",
    },
    {
        id: 'india_ins_hansa',
        name: 'INS Hansa (Goa)',
        lat: 15.3877,
        lon: 73.8354,
        type: 'india',
        country: 'India',
        arm: 'Indian Navy (Air)',
        status: 'active',
        description: 'Dabolim, Goa. Naval air station.',
    },
    {
        id: 'india_andaman_cmd',
        name: 'Andaman & Nicobar Command',
        lat: 11.6234,
        lon: 92.7265,
        type: 'india',
        country: 'India',
        arm: 'Tri-Service',
        status: 'active',
        description: "Port Blair. India's only tri-service command. Monitors Malacca approaches.",
    },
    {
        id: 'india_ins_baaz',
        name: 'INS Baaz (Campbell Bay)',
        lat: 7.0000,
        lon: 93.9230,
        type: 'india',
        country: 'India',
        arm: 'Indian Navy (Air)',
        status: 'active',
        description: 'Southernmost Indian air station. ~90 NM from Malacca Strait.',
    },
    {
        id: 'india_naval_academy',
        name: 'Indian Naval Academy (INS Zamorin)',
        lat: 11.8908,
        lon: 75.3989,
        type: 'india',
        country: 'India',
        arm: 'Indian Navy',
        status: 'active',
        description: 'Ezhimala, Kerala. Primary naval training academy.',
    },

    // ═══ INDIAN AIR FORCE — COMMANDS & STATIONS ═══
    {
        id: 'india_iaf_hq',
        name: 'Air Headquarters (Vayu Bhawan)',
        lat: 28.6215,
        lon: 77.2145,
        type: 'india',
        country: 'India',
        arm: 'Indian Air Force HQ',
        status: 'active',
        description: 'Vayu Bhawan, Rafi Marg, New Delhi.',
    },
    {
        id: 'india_iaf_hindon',
        name: 'Hindon Air Force Station',
        lat: 28.7075,
        lon: 77.3590,
        type: 'india',
        country: 'India',
        arm: 'Indian Air Force',
        status: 'active',
        description: "Asia's largest air force station. Ghaziabad, UP.",
    },
    {
        id: 'india_iaf_ambala',
        name: 'Ambala Air Force Station',
        lat: 30.3704,
        lon: 76.8173,
        type: 'india',
        country: 'India',
        arm: 'Indian Air Force',
        status: 'active',
        description: 'Haryana. Rafale squadron (Golden Arrows). Frontline base.',
    },
    {
        id: 'india_iaf_jodhpur',
        name: 'Jodhpur Air Force Station',
        lat: 26.2513,
        lon: 73.0489,
        type: 'india',
        country: 'India',
        arm: 'Indian Air Force',
        status: 'active',
        description: 'Rajasthan. Western sector fighter base.',
    },
    {
        id: 'india_iaf_jaisalmer',
        name: 'Jaisalmer Air Force Station',
        lat: 26.8880,
        lon: 70.8649,
        type: 'india',
        country: 'India',
        arm: 'Indian Air Force',
        status: 'active',
        description: 'Rajasthan. Desert sector. Near Pakistan border.',
    },
    {
        id: 'india_iaf_pathankot',
        name: 'Pathankot Air Force Station',
        lat: 32.2339,
        lon: 75.6247,
        type: 'india',
        country: 'India',
        arm: 'Indian Air Force',
        status: 'active',
        description: 'Punjab. Critical northern border air station.',
    },
    {
        id: 'india_iaf_srinagar',
        name: 'Srinagar Air Force Station',
        lat: 34.0116,
        lon: 74.8016,
        type: 'india',
        country: 'India',
        arm: 'Indian Air Force',
        status: 'active',
        description: 'J&K. Key operational base for Kashmir region.',
    },
    {
        id: 'india_iaf_leh',
        name: 'Leh Air Force Station (Kushok Bakula)',
        lat: 34.1359,
        lon: 77.5465,
        type: 'india',
        country: 'India',
        arm: 'Indian Air Force',
        status: 'active',
        description: 'Ladakh. High-altitude base. LAC operations. 10,682 ft elevation.',
    },
    {
        id: 'india_iaf_tezpur',
        name: 'Tezpur Air Force Station',
        lat: 26.7089,
        lon: 92.7847,
        type: 'india',
        country: 'India',
        arm: 'Indian Air Force',
        status: 'active',
        description: 'Assam. Eastern sector. Covers Arunachal Pradesh LAC.',
    },
    {
        id: 'india_iaf_chabua',
        name: 'Chabua Air Force Station',
        lat: 27.4870,
        lon: 95.1105,
        type: 'india',
        country: 'India',
        arm: 'Indian Air Force',
        status: 'active',
        description: 'Assam. Easternmost major air base. Su-30MKI squadron.',
    },
    {
        id: 'india_iaf_hashimara',
        name: 'Hashimara Air Force Station',
        lat: 26.6941,
        lon: 89.3612,
        type: 'india',
        country: 'India',
        arm: 'Indian Air Force',
        status: 'active',
        description: 'West Bengal. Siliguri corridor. Rafale squadron.',
    },
    {
        id: 'india_iaf_thanjavur',
        name: 'Thanjavur Air Force Station',
        lat: 10.7225,
        lon: 79.1013,
        type: 'india',
        country: 'India',
        arm: 'Indian Air Force',
        status: 'active',
        description: 'Tamil Nadu. Su-30MKI with BrahMos. Indian Ocean coverage.',
    },
    {
        id: 'india_iaf_car_nicobar',
        name: 'Car Nicobar Air Force Station',
        lat: 9.1523,
        lon: 92.8196,
        type: 'india',
        country: 'India',
        arm: 'Indian Air Force',
        status: 'active',
        description: 'A&N Islands. Strategic Indian Ocean forward air base.',
    },
    {
        id: 'india_iaf_pune',
        name: 'Pune Air Force Station (Lohegaon)',
        lat: 18.5822,
        lon: 73.9197,
        type: 'india',
        country: 'India',
        arm: 'Indian Air Force',
        status: 'active',
        description: 'Maharashtra. Fighter + transport base.',
    },
    {
        id: 'india_iaf_bareilly',
        name: 'Bareilly Air Force Station',
        lat: 28.4228,
        lon: 79.4508,
        type: 'india',
        country: 'India',
        arm: 'Indian Air Force',
        status: 'active',
        description: 'UP. MiG-29 squadron. Central Command air assets.',
    },
    {
        id: 'india_iaf_gwalior',
        name: 'Gwalior Air Force Station',
        lat: 26.2934,
        lon: 78.2278,
        type: 'india',
        country: 'India',
        arm: 'Indian Air Force',
        status: 'active',
        description: 'MP. Mirage 2000 squadron. Strategic reserve.',
    },
];
